config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searchs#search",as: 'search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
    resource:favorites,only: [:create,:destroy]
    resources:book_comments,only: [:create,:destroy]
  end
  resources :users, only: [:index,:show,:edit,:update]do
    resource :relationships,only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many:favorites,dependent: :destroy
  has_many:book_comments,dependent: :destroy
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


def self.search(search, word)
    if search == "forward_match"
          Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
          Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
          Book.where(title: "#{word}")
    elsif search == "partial_match"
          Book.where("title LIKE?","%#{word}%")
    else
          Book.all
    end
end
  

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to:user
    belongs_to:book
    
    validates:comment,presence:true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
    
    belongs_to:user
    belongs_to:book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :following,class_name: 'User'
    belongs_to :follower,class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:books,dependent: :destroy
  has_many:favorites,dependent: :destroy
  has_many:book_comments,dependent: :destroy
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}

  has_many :relationships,foreign_key: :following_id,dependent: :destroy
  has_many :followings,through: :relationships,source: :follower
  
  has_many :reverse_of_relationships,class_name: "Relationship",foreign_key: :follower_id,dependent: :destroy
  has_many :followers,through: :reverse_of_relationships,source: :following
  

def self.search(search,word)
  if search == "forward_match"
    User.where("name LIKE?","#{word}%")
  elsif search == "backward_match"
    User.where("name LIKE?","%#{word}")
  elsif search == "perfect_match"
    User.where(name: "#{word}")
  elsif search == "partial_match"
    User.where("name LIKE?","%#{word}%")
  else
    User.all
  end
end

  def get_profile_image(size)
      unless profile_image.attached?
        file_path=Rails.root.join('app/assets/images/no_image.jpg')
        profile_image.attach(io: File.open(file_path),filename: 'default_image.jpg',content_type: "image/jpeg")
      end
    profile_image.variant(resize: size).processed
  end
  
  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

end

    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
    def create
        @comment=current_user.book_comments.new(book_comment_params)
        @comment.book_id=params[:book_id]
        @comment.save
    end
    
    def destroy
        @comment=current_user.book_comments.find(params[:id])
        @comment.destroy
    end
    
    private
    def book_comment_params
        params.require(:book_comment).permit(:comment)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment=BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    redirect_to books_path unless current_user.id == @book.user_id
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        @book=Book.find(params[:book_id])
        favorite=current_user.favorites.new(book_id: @book.id)
        favorite.save
    end
    
    def destroy
        @book=Book.find(params[:book_id])
        favorite=current_user.favorites.find_by(book_id: @book.id)
        favorite.destroy
    end
    
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :authenticate_user!
    def create
        following=current_user.relationships.build(follower_id: params[:user_id])
        following.save
        redirect_to request.referrer || root_path
    end
    
    def destroy
        following=current_user.relationships.find_by(follower_id: params[:user_id])
        following.destroy
        redirect_to request.referrer || root_path
    end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
def search
    @range = params[:range]
    search = params[:search]
    @word = params[:word]

    if @range == "1"
      @user = User.search(search,@word)
    else
      @book = Book.search(search,@word)
    end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def index
    @users = User.all
    @book = Book.new
  end
 
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end


  def edit
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless current_user.id == @user.id
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end
  
  def followings
    user=User.find(params[:id])
    @users=user.followings
  end
  
  def followers
    user =User.find(params[:id])
    @users=user.followers
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_index.erb
     <table cellpadding="5">
       <%book.book_comments.each do |book_comment|%>
        <tr>
          <td>
            <%=link_to (book_comment.user)do%>
              <%=image_tag book_comment.user.get_profile_image("50x50")%><br>
              <%=book_comment.user.name%>
            <%end%>
          </td>
          <td><%=book_comment.comment%></td>
          <td>
          <%if book_comment.user==current_user%>
            <%=link_to book_book_comment_path(book_comment.book,book_comment),method: :delete,remote:true do%>
              <button type="button" class="btn btn-danger">Destroy</button>
            <%end%>
          <%end%>
          </td>
        </tr>
       <%end%>
      </table>

app/views/book_comments/_index.html.erb
     <table cellpadding="5">
       <%book.book_comments.each do |book_comment|%>
        <tr>
          <td>
            <%=link_to (book_comment.user)do%>
              <%=image_tag book_comment.user.get_profile_image("50x50")%><br>
              <%=book_comment.user.name%>
            <%end%>
          </td>
          <td><%=book_comment.comment%></td>
          <td>
          <%if book_comment.user==current_user%>
            <%=link_to book_book_comment_path(book_comment.book,book_comment),method: :delete,remote:true do%>
              <button type="button" class="btn btn-danger">Destroy</button>
            <%end%>
          <%end%>
          </td>
        </tr>
       <%end%>
      </table>

app/views/book_comments/create.js.erb
$('#book_comment_<%=@comment.book.id%>').html("<%= j(render 'book_comments/index',book: @comment.book)%>");
$("textarea").val('');

app/views/book_comments/destroy.js.erb
$('#book_comment_<%=@comment.book.id%>').html("<%= j(render 'book_comments/index',book: @comment.book)%>");

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		 <%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'layouts/errors', obj: @book %>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to(book.user) do %>
                <%= image_tag book.user.get_profile_image("50x50") %>
                <% end %>
              </td>
              <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
              <td><%= book.body %></td>
              
              <td id="favorite_btn_<%=book.id%>">
                <%=render 'favorites/favorite', book: book%>
              </td>
              
              <td>
                コメント数:<%=book.book_comments.count%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info',user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image("50x50") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <%if @book.user==current_user%>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <%end%>
          
          <td id="favorite_btn_<%=@book.id%>">
            <%=render 'favorites/favorite',book: @book%>
          </td>
          
          <td>
            <p>
              コメント数:<%=@book.book_comments.count%>
            </p>
          </td>
        </tr>
      </table>
      
      <div id="book_comment_<%=@book.id%>">
        <%=render 'book_comments/index',book: @book%>
      </div>
      
      <div>
        <%=form_with model: [@book,@book_comment],remote:true do |f|%>
            <%=f.text_area :comment,cols:80,rows:5%><br>
            <%=f.submit'送信'%>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
<%if book.favorited_by?(current_user)%>
    <p>
    <%=link_to book_favorites_path(book),method: :delete,remote:true do%>
        ❤️<%=book.favorites.count%>
    <%end%>
    </p>
<%else%>
    <p>
    <%=link_to book_favorites_path(book),method: :post,remote:true do%>
        🤍<%=book.favorites.count%>
    <%end%>
    </p>
<%end%>

app/views/favorites/create.js.erb
$('#favorite_btn_<%=@book.id%>').html("<%= j(render 'favorites/favorite', book: @book )%>");

app/views/favorites/destroy.js.erb
$('#favorite_btn_<%=@book.id%>').html("<%= j(render 'favorites/favorite', book: @book) %>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/searchs/_form.html.erb
<div class="text-center">
<% if user_signed_in? %>

   <%= form_tag(search_path, method: :get) do %>
   
      <%= text_field_tag (:word) %>

   <%= select_tag 'range' ,options_for_select([ ['User', '1'], ['Book', '2']]) %>

         <%= select_tag 'search', options_for_select([ ["完全一致","perfect_match"],["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
         <%= submit_tag "検索" %>

   <% end %>

<% end %>
</div>

app/views/searchs/search.html.erb
<table class="table table-hover table-inverse">
 <% if @range == '2' %>
 <h1>Books search for '<%=@word%>'</h1>
  <thead>
    <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
     <% @book.each do |book| %>
     <tr>
      <td>
       <%=image_tag book.user.get_profile_image("50x50") %>
      </td>
      <td>
       <%= link_to book.title, book, class: "book_#{book.id}" %> 
      </td>
      <td><%= book.body %></td>
     </tr>
     <% end %>
  </tbody>

  <% else %>
  <h1>Users search for '<%=@word%>'</h1>
  <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
     </tr>
   </thead>

   <tbody>
    <% @user.each do |user| %>
     <tr>
      <td><%= image_tag user.get_profile_image("50x50") %></td>
      <td><%= user.name%></td>
      <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
     </tr>
    <% end %>
   </tbody>
   <% end %>
 </table>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
      <th colspan="4"></th>
      <th colspan="5"></th>
      <th colspan="6"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image("50x50") %></td>
        <td><%= user.name %></td>
        <td>フォロー数<%=link_to user.followings.count,followings_user_path(user)%></td>
        <td>フォロワー数<%=link_to user.followers.count,followers_user_path(user)%></td>
          <%if user == current_user%>
            <td>&nbsp;</td>
          <%else%>
            <td>
              <%if user.is_followed_by?(current_user)%>
                <%=link_to user_relationships_path(user), method: :delete do %>
                <p>フォロー外す</p>
                <% end %>
              <%else%>
                <%=link_to user_relationships_path(user), method: :post do %>
                <p>フォローする</p>
                <% end %>
              <%end%>
            </td>
          <%end%>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image("100x100") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>followes</th>
    <th><%=link_to user.followings.count,followings_user_path(user)%></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%=link_to user.followers.count,followers_user_path(user)%></th>
  </tr>
  <tr>
    <th>
     <% if user != current_user %>
        <% if user.is_followed_by?(current_user) %>
          <%=link_to user_relationships_path(user), method: :delete do %>
            <button type="button" class="btn btn btn-danger">フォロー外す</button>
          <% end %>
        <% else %>
          <%=link_to user_relationships_path(user), method: :post do %>
            <button type="button" class="btn btn btn-primary">フォローする</button>
          <% end %>
        <% end %>
     <% end %>
    </th>
  </tr>
</table>
　
<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h1>Follower Users</h1>
    <%if @users.empty?%>
        <p>ユーザーはいません</p>
    <%else%>
          <table class="table">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
                <th colspan="4"></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                      <%=link_to user_path(user) do%>
                      <%=image_tag user.get_profile_image("50x50")%>
                      <%end%>
                  </td>
                  <td>
                    <%= link_to user_path(user) do %>
                      <%= user.name %>
                    <% end %>
                  </td>
                  <td>フォロー数<%=link_to user.followings.count,followings_user_path(user)%></td>
                  <td>フォロワー数<%=link_to user.followers.count,followers_user_path(user)%></td>
                </tr>
              <% end %>
            </tbody>
          </table>
    <%end%>

app/views/users/followings.html.erb
<h1>Follow Users</h1>
    <%if @users.empty?%>
        <p>ユーザーはいません</p>
    <%else%>
          <table class="table">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
                <th colspan="4"></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                      <%=link_to user_path(user) do%>
                      <%=image_tag user.get_profile_image("50x50")%>
                      <%end%>
                  </td>
                  <td>
                    <%= link_to user_path(user) do %>
                      <%= user.name %>
                    <% end %>
                  </td>
                  <td>フォロー数<%=link_to user.followings.count,followings_user_path(user)%></td>
                  <td>フォロワー数<%=link_to user.followers.count,followers_user_path(user)%></td>
                </tr>
             <% end %>
            </tbody>
          </table>
    <%end%>

app/views/users/index.html.erb
<div class='container '>
    <div class='row'>
        <div class='col-md-3'>
<h2>User info</h2>
<%= render 'info', user: current_user %>

<h2 class="mt-3">New book</h2>
<%= render 'books/form', book: @book %>
        </div>
        
        <div class='col-md-8 offset-md-1'>
<h2>Users</h2>
<%= render 'index',users: @users %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to(book.user) do %>
                <%= image_tag book.user.get_profile_image("50x50") %>
                <% end %>
              </td>
              <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
              <td><%= book.body %></td>
              
              <td id="favorite_btn_<%=book.id%>">
                <%=render 'favorites/favorite', book: book%>
              </td>
              
              <td>
                コメント数:<%=book.book_comments.count%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>